### ISSUE TITLE
Plugin is not available from Ultimaker Marketplace

### ISSUE THREAD

**Issue by Simonlebucheron** [5axes/NameIt#15]
Hi, I cannot find the plugin either on the Ultimaker marketplace or from the install instance of Cura 5.1. Even if I search in all plugins from "5axes". Is it normal ? 
<img width="960" alt="2022-08-14" src="https://user-images.githubusercontent.com/81119914/184545588-6fbc0fc8-b4e6-4a08-af27-ca5692125b28.png">

**Comment by 5axes** [comment]
Yes it's "normal" Ultimaker removed the plugin about 15 days ago. The plugin was using Windows fonts and apparently converting a Police into STL does not respect the license even they are free.  To avoid problems I replaced the 2 Polices by new ones on the advice of Ghostkeeper. But I'll have to wait for Ultimaker's validation. In the meantime, the online version can be used :  https://github.com/5axes/NameIt/releases/tag/V1.8.0

**Comment by Simonlebucheron** [comment]
Ok thanks for the quick answer. Very nice and useful work by the way.
