### ISSUE TITLE
Uses Body name instead of part name

### ISSUE THREAD

**Issue by adman120** [5axes/NameIt#17]
When Trying to add the part name, NameIT only uses the bodynames instead. 
![image](https://user-images.githubusercontent.com/3687746/199747481-0f45be96-6ea6-45a2-adb0-92bc94a83dbe.png)
Should be Line 5 mount, but only shows up as bodies

**Comment by 5axes** [comment]
Sample file ?

**Comment by 5axes** [comment]
No answer, I think I can close this release
