### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by smokeandlights** [5axes/NameIt#25]
It would be awesome if this could print the first X characters of the file name, or custom labels that could be input manually.

**Comment by 5axes** [comment]
In principle, this can be done using the Rename function in the plugin. Simply select the elements to be renamed, give the first X characters, and then use the NameIt to creates the labels.   For me  this approach may take a little longer, but it's more flexible if you have several different types of part on the bed.

![image](https://github.com/5axes/NameIt/assets/11015345/8fac6206-8308-4afd-b917-0b11e5147075)

**Comment by 5axes** [comment]
You can also use the Number Prefix to define your custom labels.
![image](https://github.com/5axes/NameIt/assets/11015345/9e02cfbf-999a-40da-9c49-6a251198f3f4)

**Comment by 5axes** [comment]
No feedback I think I can close this request
