### ISSUE TITLE
Auto ID-ing of multiplies

### ISSUE THREAD

**Issue by ImagineerNL** [5axes/NameIt#4]
Not sure if this is even possible since 'multiply' of objects is a cura feature.
If you currently multiply an ID'd object, the copies have the same ID, but do get the new object name 'object (2).stl'

'fixing' this might need an extra look at what happens when an ID is already in use for that object 
(for example; object.stl ID1, object(1).stl ID2 and creating a copy of object.stl... that would create an object(2).stl but would the ID be 2 or 3?)

**Comment by 5axes** [comment]
The current version of ManeIt is now V1.0.1 this issue should not exist anymore

**Comment by ImagineerNL** [comment]
Well its easy; when theres no number, start with 0
The numbering is usually only important when having multiple copies, so only a 0 wouldnt occur.
If you trick, re-arrange and define the '' as '1', the (1) as '2' etc you will eventually get other referencing issues in the Object List (bottom left)

![image](https://user-images.githubusercontent.com/62603552/174486660-a049fbf0-ebca-4d35-86c8-fe05f181bb6f.png)

Luckily it seems they fixed cura5 where in cura 4 creating a copy of 'object.stl(1)' created 'object.stl(1)(1)', but now it is correctly named 'object.stl(2)' of if that already existed it is 'object.stl(3)'

Different ID for different objects (object1.stl(1...3) and object2.stl(1...3) can be an issue and might be resolved with an 1.1..3 2.1..3

But then we might be stretching the usecases :)

**Comment by 5axes** [comment]
New Function : Add Number From Part
https://github.com/5axes/NameIt/releases/tag/V1.1.0

**Comment by 5axes** [comment]
V1.2.0 -> V1.3.0 If no Number exist in the name then do nothing but a message will inform you that only some element have been created. The last number is keep in memory so selecting the object withour number and using the add number function will create  the missing identifier

**Comment by 5axes** [comment]
The Rename Models function integrated in the last release give an other solution to this issue
